tindzk/seed

.gitignore
Dockerfile
build.sbt
src/main/scala/seed/generation/Bloop.scala
src/test/scala/seed/generation/BloopIntegrationSpec.scala
src/test/scala/seed/generation/util/ProcessHelper.scala

- `scalaCompiler` is optional on meta modules and can be set to None
- Introduce helper functionality for spawning processes
- Write integration test for generating and compiling a meta module
- Build: Update minitest dependency

Bloop: Set correct dependencies on meta modules

---

.drone.yml
Dockerfile
build.sh

Only publish artefacts for the `master` branch, while continuing to test builds from development branches.
Exclude pull requests from the `publish` pipeline.
Also factor out csbt commands from Dockerfile into a separate file for better reuse.

Drone CI: Move testing logic to separate pipeline

---

src/main/scala/seed/artefact/Coursier.scala
src/main/scala/seed/generation/Idea.scala
src/test/scala/seed/artefact/ArtefactResolutionSpec.scala
src/test/scala/seed/artefact/CoursierSpec.scala

JavaScript and native dependencies were ignored because the two parameters `platformVersion` and `compilerVersion` had been mixed up.
Add a `require()` to `resolveSubset()` in order to enforce that a valid set of dependencies is passed.

Idea: Fix dependency resolution of platform dependencies

---

src/main/scala/seed/artefact/Coursier.scala
src/main/scala/seed/cli/Build.scala
src/main/scala/seed/config/BuildConfig.scala
src/main/scala/seed/generation/Idea.scala
src/test/scala/seed/config/BuildConfigSpec.scala
src/test/scala/seed/generation/IdeaSpec.scala

When a build file imported external modules, the `idea` command could fail with an exception thrown by `relativize()`. This commit addresses various corner cases and consolidates the logic for path normalisation.
Also, `BuildConfig` was changed to prefer a relative build project path as this value gets propagated to the generators.
The new tests could result in multiple dependency resolutions being triggered at the same time if artefacts were not cached locally. This was causing Drone CI builds to fail. Avoid concurrent access during dependency resolution by using a re-entrant lock.
Finally, make sure that the logger is only initialised once.

Idea: Fix path normalisation

---

src/main/scala/seed/artefact/ArtefactResolution.scala
src/main/scala/seed/artefact/Coursier.scala
src/main/scala/seed/config/BuildConfig.scala
src/main/scala/seed/model/Build.scala
src/test/scala/seed/artefact/ArtefactResolutionSpec.scala
src/test/scala/seed/config/BuildConfigSpec.scala

Pull request #6 uncovered a problem in `ArtefactResolution`: When a test module did not set any target platforms, its dependencies would not be resolved.
Currently, the logic in `BuildConfig` only considers the platform-specific modules defined on a test module. Change the logic to inherit all targets from the parent module.
Change the type of `import` on `Build` to `Path` to avoid the duplicated normalisation logic of `fixPath()`.
Also, break `load()` on `Build` apart into separate functions to allow for better testing.

Inherit target platforms on test modules

---

.gitignore
README.md
src/main/scala/seed/artefact/ArtefactResolution.scala
src/main/scala/seed/artefact/Coursier.scala
src/main/scala/seed/artefact/MavenCentral.scala
src/main/scala/seed/cli/Package.scala
src/main/scala/seed/cli/Scaffold.scala
src/main/scala/seed/cli/Update.scala
src/main/scala/seed/config/BuildConfig.scala
src/main/scala/seed/config/util/TomlUtils.scala
src/main/scala/seed/generation/Bloop.scala
src/main/scala/seed/generation/Idea.scala
src/main/scala/seed/model/Artefact.scala
src/main/scala/seed/model/Build.scala
src/test/scala/seed/artefact/ArtefactResolutionSpec.scala
src/test/scala/seed/artefact/CoursierSpec.scala
src/test/scala/seed/config/BuildConfigSpec.scala

Currently, the version tag for dependencies in the TOML file always
encodes the platform name and binary Scala version. Internally,
Seed already has to handle different version tags. Expose this
functionality in `scalaDep` by introducing a fourth parameter. The
detailed changes for this are:
- `Build`: Introduce `VersionTag` which was previously called
`PlatformSuffix` and located in `Artefact`
- `Build`: Make `Dep` a sealed trait with two children, `JavaDep` and
`ScalaDep`, the only difference between those two being that
`ScalaDep` has a `VersionTag` parameter. The version tag defaults
to `PlatformBinary` in order to retain compatibility.
- `TomlUtils`: Introduce codec for parsing `VersionTag` values
- `Artefact`: Remove `Versioned` in favour of `Dep`
- `Artefact`: Provide function for …

 Expose artefact version tag in TOML build file

---

README.md
build.sbt
src/main/scala/seed/Cli.scala
src/main/scala/seed/Log.scala
src/main/scala/seed/build/Link.scala
src/main/scala/seed/cli/Build.scala
src/main/scala/seed/cli/BuildEvents.scala
src/main/scala/seed/cli/Link.scala
src/main/scala/seed/cli/Server.scala
src/main/scala/seed/cli/Update.scala
src/main/scala/seed/cli/util/ArgyleHelpers.scala
src/main/scala/seed/cli/util/BloopCli.scala
src/main/scala/seed/cli/util/WsClient.scala
src/main/scala/seed/cli/util/WsServer.scala
src/main/scala/seed/config/BuildConfig.scala
src/main/scala/seed/config/SeedConfig.scala
src/main/scala/seed/config/util/TomlUtils.scala
src/main/scala/seed/model/BuildEvent.scala
src/main/scala/seed/process/ProcessHelper.scala
src/test/scala/seed/build/LinkSpec.scala
src/test/scala/seed/config/BuildConfigSpec.scala
src/test/scala/seed/generation/BloopIntegrationSpec.scala
src/test/scala/seed/generation/util/ProjectGeneration.scala
src/test/scala/seed/generation/util/TestProcessHelper.scala

- `Cli`: Add new commands `server`, `link` and `buildEvents`
- `Log`: Make underlying printer customisable
- `BuildConfig`: Take `Log` parameter to allow forwarding of log messages
- `BuildConfig`, `TomlUtils`: Gracefully handle errors instead of exiting program
- `BuildConfig`: Add `linkTargets()` to determine all possible link targets of a module
- `ArgyleHelpers`: Introduce Argyle parser for flags that take an optional value
- `BloopCli`: Introduce helper object for interacting with Bloop and parsing its output
- `WsServer`: Introduce WebSocket server based on Java WebSockets
- `WsCommand`: Define JSON protocol for WebSocket server including Circe codecs
- `BloopIntegrationSpec`: Move project generation logic to `ProjectGeneration` for better reuse

Implement link command and WebSocket interface

---

build.sh
src/main/scala/seed/artefact/ArtefactResolution.scala
src/main/scala/seed/generation/Bloop.scala
src/main/scala/seed/generation/Idea.scala
src/main/scala/seed/generation/util/ScalaCompiler.scala
src/test/scala/seed/generation/BloopIntegrationSpec.scala
src/test/scala/seed/generation/IdeaSpec.scala
test/compiler-options/build.toml
test/multiple-scala-versions/build.toml
test/multiple-scala-versions/module211/src/Main.scala
test/multiple-scala-versions/module212/src/Main.scala

- **Bloop:** When determining the class path for compiler plug-ins, use the Scala version of the module instead of the global compiler version
- **IDEA:** Generate modules with the correct Scala version and compiler options

Honour Scala version mandated by modules

---

.drone.yml

Since `branch` cannot be used in conjunction with `event: tag`,
create two separate CI steps, one for publishing pre-releases (i.e.
any push to `master`) and another for releases (i.e. any tagged
commit).
See also 5f48fa5.

Drone CI: Only publish when pushing to master or releasing a version

---

src/main/scala/seed/generation/Bloop.scala
src/test/scala/seed/build/LinkSpec.scala
src/test/scala/seed/generation/BloopIntegrationSpec.scala
src/test/scala/seed/generation/BloopSpec.scala
src/test/scala/seed/generation/util/ProjectGeneration.scala

When generating a Bloop project, Java dependencies specified on base
modules should be inherited and added to the class path of all child
modules. These changes make the behaviour of `javaDeps` consistent
with `scalaDeps`.

Bloop: Inherit javaDeps from parent modules

---

src/main/scala/seed/generation/Idea.scala
src/main/scala/seed/generation/util/IdeaFile.scala
src/test/scala/seed/generation/IdeaSpec.scala

This setting is required for IDEA to know whether certain
version-specific features are available (such as literal types in
2.13).

IDEA: Set language level for Scala library

---

src/main/scala/seed/Cli.scala
src/main/scala/seed/cli/BuildTarget.scala
src/main/scala/seed/cli/Package.scala
src/main/scala/seed/config/BuildConfig.scala
src/main/scala/seed/generation/Bloop.scala
src/main/scala/seed/generation/Idea.scala
src/main/scala/seed/generation/util/PathUtil.scala
src/test/scala/seed/generation/IdeaSpec.scala
src/test/scala/seed/generation/util/PathUtilSpec.scala
src/test/scala/seed/generation/util/ProjectGeneration.scala

Currently, if tmpfs is disabled, `BuildTarget` uses an output path
that is different from the generated Bloop project. Introduce
`PathUtil` to unify the build path logic across the entire code base
and write test cases.
Also, change the path of the linked Bloop artefacts from
`build/bloop/` to `build/`. When packaging modules, place `dist/`
under the same build path.
Further changes:
- Idea: Move `normalisePath()` to `PathUtil`
- `Cli`: Improve help

Refactor build path logic

---

src/main/scala/seed/Log.scala
src/main/scala/seed/cli/Build.scala
src/main/scala/seed/cli/BuildTarget.scala
src/main/scala/seed/cli/Link.scala
src/main/scala/seed/cli/util/BloopCli.scala
src/main/scala/seed/cli/util/Exit.scala
src/main/scala/seed/process/ProcessHelper.scala
src/test/scala/seed/build/LinkSpec.scala
src/test/scala/seed/generation/BloopIntegrationSpec.scala
src/test/scala/seed/generation/util/TestProcessHelper.scala
test/custom-command-target-fail/build.toml
test/custom-command-target-fail/demo/Main.scala

Currently, the build process continues when a command is not found
or exits with a non-zero code. This is undesired in CI setups as the
developers would not be aware of any problems related to custom
build targets.

ProcessHelper: Exit when command returned with non-zero code

---

src/main/scala/seed/cli/Scaffold.scala
src/main/scala/seed/generation/util/PathUtil.scala
src/test/scala/seed/cli/ScaffoldSpec.scala
src/test/scala/seed/generation/util/PathUtilSpec.scala

- Do not fail if a non-JVM platform was selected
- Drop all `scalaOptions`
- `-Xfuture` has been deprecated in Scala 2.13
- The other Scala options are not essential for a minimum working
build file either and can be removed
- If no test frameworks were selected, do not set `testFrameworks`,
add test modules or create any test folders
- Mark Typelevel Scala as legacy
- Improve formatting of questions
- Reduce output when user provided invalid input
- Test frameworks: Accept "none" as input since it is the indicated
default value
- When there can be multiple options, allow spaces before/after the
comma
- Fix crash when selecting Typelevel Scala, pre-releases and several
test frameworks
- Fix bug which did not allow users to specify a custom file path:
`seed init --build=test.toml`
If we go …

Improve scaffold command

---

src/main/scala/seed/Cli.scala
src/main/scala/seed/cli/Package.scala
src/main/scala/seed/config/util/TomlUtils.scala
src/main/scala/seed/generation/Package.scala
src/test/scala/seed/generation/PackageSpec.scala
src/test/scala/seed/generation/util/TestProcessHelper.scala
test/package-modules/app/src/example/Main.scala
test/package-modules/build.toml
test/package-modules/core/src/example/Core.scala

Presently, an exception occurs if two modules share the same package
name. Change the behaviour in order not to add the same entry twice.
If the same compiled class file exists in multiple modules, issue a
warning. Also, break `Package` apart into smaller functions for
better readability.

Package: Skip entries that were already added to the JAR file

---

src/main/scala/seed/artefact/ArtefactResolution.scala
src/main/scala/seed/artefact/Coursier.scala
src/main/scala/seed/generation/util/ScalaCompiler.scala
src/test/scala/seed/artefact/ArtefactResolutionSpec.scala
src/test/scala/seed/artefact/CoursierSpec.scala
src/test/scala/seed/generation/BloopIntegrationSpec.scala
test/example-paradise-platform/build.toml
test/example-paradise-platform/example/Test.scala
test/example-paradise-platform/macros/Macros.scala
test/example-paradise-versions/build.toml
test/example-paradise-versions/example/Test.scala
test/example-paradise-versions/macros/Macros.scala

- ScalaCompiler: Include compiler plug-ins defined on platform
module
- Coursier: Only return artefact path if requested version matches
Closes #16.

Fix inheritance of compiler plug-ins

---

src/main/scala/seed/cli/BuildTarget.scala
src/main/scala/seed/generation/Bloop.scala
test/custom-command-target/build.toml

If Seed is configured to compile to tmpfs and the operating system
is restarted, the build path disappears. Afterwards, commands such
as `cp -R <directory> $BUILD_PATH` will behave differently.
These changes will create the directory in `BuildTarget` prior to
the execution of any commands.

BuildTarget: Create build path if it does not exist

---

.gitignore
src/main/scala/seed/Cli.scala
src/main/scala/seed/cli/Build.scala
src/main/scala/seed/cli/Generate.scala
src/main/scala/seed/cli/Server.scala
src/main/scala/seed/generation/Bloop.scala
src/main/scala/seed/generation/Idea.scala
src/main/scala/seed/generation/util/PathUtil.scala
src/test/scala/seed/build/LinkSpec.scala
src/test/scala/seed/config/BuildConfigSpec.scala
src/test/scala/seed/generation/BloopIntegrationSpec.scala
src/test/scala/seed/generation/BloopSpec.scala
src/test/scala/seed/generation/IdeaSpec.scala
src/test/scala/seed/generation/PackageSpec.scala
src/test/scala/seed/generation/util/BuildUtil.scala
src/test/scala/seed/generation/util/ProjectGeneration.scala

- Use `createTempDirectory` instead of `/tmp` for better portability
- PathUtil: Use `normalisePath` as `getCanonicalPath` resolves
symbolic links
The first change makes the test suite compatible with macOS.
Closes #30.

Build all test projects in temporary folder

---

src/main/scala/seed/generation/Bloop.scala
src/main/scala/seed/model/Build.scala
src/test/scala/seed/generation/BloopIntegrationSpec.scala
test/submodule-output-path/build.toml
test/submodule-output-path/src/Main.scala
test/submodule-output-path/submodule/build.toml
test/submodule-output-path/submodule/src/Main.scala

Currently, the output path of a submodule includes the relative path
to its build file, although it should only be relative to the root
project's build path.
Another limitation that these changes address is that the output
folder was not created by Seed such that Bloop might fail to link
the project.

Bloop: Fix output path of submodules

---

src/main/scala/seed/artefact/MavenCentral.scala
src/test/scala/seed/artefact/MavenCentralSpec.scala

If an organisation contains multiple artefacts with the same prefix
followed by a digit, this digit would be considered as part of the
version:
```
✗ Could not parse version '8_2.12'. Falling back to comparison by natural ordering...
✗ Could not parse version '8_2.13'. Falling back to comparison by natural ordering...
✗ Could not parse version '8_2.13.0-RC2'. Falling back to comparison by natural ordering...
✗ Could not parse version '8_2.13.0-RC2'. Falling back to comparison by natural ordering...
[...]
```
These errors were reported to the user when running `seed update` on
projects that use the `scribe-slf4j` dependency.

MavenCentral: Fix parsing of library artefacts

---

src/main/scala/seed/cli/Scaffold.scala
src/test/scala/seed/cli/ScaffoldSpec.scala

If Typelevel Scala 2.12.4 is used along with Scala.js, the latest
compiler version could not be determined during `seed update`:
```
Platform compiler versions
╭────────────┬──────────────┬──────────┬────────────────────────╮
│ Platform   │ Organisation │ Compiler │ Version                │
├────────────┼──────────────┼──────────┼────────────────────────┤
│ JVM        │ Typelevel    │ Scala    │ 2.12.4-bin-typelevel-4 │
│ JavaScript │ Typelevel    │ Scala    │ Not available          │
│            │ Scala.js     │ Plug-in  │ Not available          │
╰────────────┴──────────────┴──────────┴────────────────────────╯
```
This is due to the fact that Scala.js supports Scala 2.13, and if
all libraries are compatible, `choosePlatformConfiguration()` would
choose 2.13 over 2.12. However, …

Scaffold: Only return compatible compiler versions

---

src/main/scala/seed/artefact/MavenCentral.scala
src/main/scala/seed/artefact/SemanticVersioning.scala
src/main/scala/seed/cli/Scaffold.scala
src/main/scala/seed/cli/Update.scala
src/test/scala/seed/artefact/SemanticVersioningSpec.scala

When updating projects with the JGit dependency, the following
exception is thrown:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "201202151440"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:583)
at java.lang.Integer.parseInt(Integer.java:615)
at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
at seed.artefact.SemanticVersioning$.parsePreReleaseParts(SemanticVersioning.scala:59)
at seed.artefact.SemanticVersioning$.parseVersion(SemanticVersioning.scala:94)
```
Changes:
- Represent pre-release versions as longs to prevent this …

SemanticVersioning: Fix parsing of large pre-release versions

---

src/main/scala/seed/config/BuildConfig.scala
src/test/scala/seed/generation/BloopIntegrationSpec.scala

When run with `--verbose`, Bloop indicates that it detected changes
on the `custom-command-target` project:
```
[D] Classpath hash changed!
[...]
+  FileHash(file: /tmp/build-custom-command-target/bloop/utils, hash: -3319929)
)
```
This directory does not exist since the custom build target does not
have any Scala sources. Filter out all dependent modules in the
classpath that do not target the same platform as the base module.

BuildConfig: Only include modules with same platform in classpath

---

src/main/scala/seed/config/BuildConfig.scala
src/test/scala/seed/generation/BloopIntegrationSpec.scala
test/duplicate-transitive-dep/build.toml

This fixes a crash when generating a Bloop project with transitively
duplicate module dependencies.
Closes #47.

BuildConfig: Avoid duplicate class paths

---

src/main/scala/seed/generation/Idea.scala
src/test/scala/seed/generation/IdeaSpec.scala
test/platform-module-deps/build.toml

Currently, only module dependencies of cross-platform modules are
set when generating an IDEA project. Also include the module
dependencies of platform-specific modules.
This fixes a regression introduced in 51a27f5.

IDEA: Set correct module dependencies

---

src/main/scala/seed/generation/Idea.scala
src/main/scala/seed/generation/util/IdeaFile.scala
src/test/scala/seed/generation/IdeaSpec.scala
test/module-scala-options/build.toml

Similarly to #52, the generation of compiler profiles for IDEA only
honoured Scala options of cross-platform modules. Take the Scala
options of platform modules instead.
Furthermore, `IdeaFile` used the wrong format to encode compiler
profiles whereby IDEA only picked up the compiler settings for the
first set of modules.

IDEA: Fix generation of projects with mixed Scala options

---

src/main/scala/seed/generation/Idea.scala
src/test/scala/seed/generation/IdeaSpec.scala

When following functions defined in the standard library, IDEA
should show their source code as with regular library dependencies.

IDEA: Set the JavaDoc and source paths on compiler libraries

---

.drone.yml
src/main/scala/seed/config/BuildConfig.scala
src/main/scala/seed/generation/Bloop.scala
src/main/scala/seed/generation/Idea.scala
src/test/scala/seed/generation/BloopIntegrationSpec.scala
src/test/scala/seed/generation/IdeaSpec.scala
test/shared-module/base/js/src/Platform.scala
test/shared-module/base/native/src/Platform.scala
test/shared-module/build.toml
test/shared-module/example/shared/src/Main.scala

The project generation assumed that cross-platform modules are
compatible with the JVM, though this is not necessarily the case.
Instead, choose a valid platform from the `targets` setting.
Changes:
- Set up correct dependencies between IDEA modules, taking into
account that not every Seed module has a corresponding IDEA module
- Do not reference invalid IDEA modules in compiler settings
- Generate IDEA modules that lack sources, but have a root path set
- Bloop: Compile and run a Scala Native program

IDEA: Fix generation of non-JVM projects

---

src/main/scala/seed/config/BuildConfig.scala
src/test/scala/seed/config/BuildConfigSpec.scala

The validation triggered a false positive for modules with custom
build targets.
The compatibility must be checked for all platform-specific modules
separately since these may depend on additional modules which are
not included on the base module.

BuildConfig: Fix validation for module platform compatibility

---

src/main/scala/seed/cli/Scaffold.scala
src/test/scala/seed/cli/ScaffoldSpec.scala

The folders `js/`, `jvm/` and `native/` only exist when multiple
platforms were chosen. Otherwise, the sources go to `src/`.
Therefore, the IDEA root path must be set to the current working
directory.

Scaffold: Set correct root path when only one platform was selected

---

src/main/scala/seed/artefact/MavenCentral.scala
src/main/scala/seed/cli/Publish.scala
src/main/scala/seed/generation/util/ScalaCompiler.scala
src/test/scala/seed/artefact/MavenCentralSpec.scala

From v1.0 onwards, the binary tag does not contain the minor version
anymore.
Closes #91.

MavenCentral: Fix resolution of Scala.js 1.0 artefacts

---

src/main/scala/seed/artefact/ArtefactResolution.scala
src/test/scala/seed/artefact/ArtefactResolutionSpec.scala
src/test/scala/seed/generation/GenerateSpec.scala
test/test-inherit-deps/build.toml

Library dependencies defined on the referenced module should be
inherited.

ArtefactResolution: Fix inheritance on test modules

---

.drone.yml
src/main/scala/seed/cli/Publish.scala
src/test/scala/seed/cli/PublishSpec.scala

The Git command execution might fail if relative paths are used.

Publish: Use absolute path when determining Git version

---

README.md
src/main/scala/seed/artefact/ArtefactResolution.scala
src/main/scala/seed/config/util/TomlUtils.scala
src/main/scala/seed/generation/Bloop.scala
src/main/scala/seed/model/Artefact.scala
src/main/scala/seed/model/Build.scala
src/test/scala/seed/artefact/ArtefactResolutionSpec.scala
src/test/scala/seed/generation/BloopIntegrationSpec.scala
src/test/scala/seed/generation/GenerateSpec.scala
src/test/scala/seed/generation/util/BloopUtil.scala
test/test-scalajs-10/build.toml
test/test-scalajs-10/test/ExampleSpec.scala

For newer Scala.js versions, the `scalajs-test-bridge` artefact must be added to the classpath.
Further changes were made to improve compatibility with the MUnit testing library:
1. Add build setting allowing to specify Scala.js module kind
2. Fix ordering of classpath in generated Bloop configuration files
**See also:**
- scalacenter/bloop#1234
- scalameta/munit#114

Add support for Scala.js 0.6.29+ and 1.0 test modules
